export const data = [
  {
    id: 0,
    name: "Cosonsen Women's Dress Deep V-Neck Long Sleeve Waist Tie Ruffle Mini Swing Skater Dresses",
    price: 39,
    img: "https://m.media-amazon.com/images/I/51YGdPjQZCL._MCnd_AC_UL320_.jpg",
    inStock: 0,
    fastDelivery: true,
    rating: 4,
    desc: "Deep V-Neck, tie waist, back zipper closure, long sleeve, flare hem, high waist, regular fit bodice. party dress",
  },
  {
    id: 1,
    name: "GOBLES Women's Sexy Long Sleeve V Neck Ruched Bodycon Mini Party Cocktail Dress",
    price: 29,
    img: "https://m.media-amazon.com/images/I/61Pntn8GI2L._MCnd_AC_UL320_.jpg",
    inStock: 0,
    fastDelivery: true,
    rating: 4,
    desc: "V-neck, high waist,long sleeve ,ruched,mini-length ,makes you fashion and sexy",
  },
  {
    id: 2,
    name: "URRU Men's Polo Shirt and Shorts Set Summer Outfits Fashion Casual Short Sleeve Polo Suit for Men 2 Piece Short",
    price: 41,
    img: "https://m.media-amazon.com/images/I/61+kwGzZB5L._AC_UL320_.jpg",
    inStock: 1,
    fastDelivery: true,
    rating: 4,
    desc: "Made with high-quality fabric for a lived in feel, the men's shorts and t shirt set",
  },
  {
    id: 3,
    name: "Calvin Klein Men's Slim Fit Dress Pant",
    price: 49,
    img: "https://m.media-amazon.com/images/I/612qOWk77EL._AC_UL320_.jpg",
    inStock: 0,
    fastDelivery: true,
    rating: 5,
    desc: "Tapered leg in a stretch comfort fabric for ease of movement",
  },
  {
    id: 4,
    name: "DREAM PAIRS Women's Chunk Low Heel Pump Sandals",
    price: 39,
    img: "https://m.media-amazon.com/images/I/61UCnpSHxPL._AC_UL320_.jpg",
    inStock: 0,
    fastDelivery: false,
    rating: 4,
    desc: "Buckle at ankle closure",
  },
  {
    id: 5,
    name: "REDTOP Women's Elastic Chelsea Boots Chunky Block Heel Platform Lug Sole Ankle Booties",
    price: 59,
    img: "https://m.media-amazon.com/images/I/71ueawXsSYL._AC_UL320_.jpg",
    inStock: 4,
    fastDelivery: true,
    rating: 2,
    desc: "Buckle at ankle closure",
  },
  {
    id: 6,
    name: "Bruno Marc Men's Leather Lined Dress Oxfords Shoes",
    price: 39,
    img: "https://m.media-amazon.com/images/I/61q5gTyVirL._AC_UL320_.jpg",
    inStock: 4,
    fastDelivery: false,
    rating: 4,
    desc: "Buckle at ankle closure",
  },
  {
    id: 7,
    name: "TEXAS STEER Men's Work Boots 6",
    price: 39,
    img: "https://m.media-amazon.com/images/I/71s9Wr5V9yL._AC_UL320_.jpg",
    inStock: 4,
    fastDelivery: true,
    rating: 3,
    desc: "Buckle at ankle closure",
  },
  {
    id: 8,
    name: "Alex and Ani Stretch Bracelet for Women, Love Heart Beads, Shiny Finish, Fits Wrists Sizes 6 to 8 in",
    price: 28,
    img: "https://m.media-amazon.com/images/I/71hlwG7B3oS._AC_UL320_.jpg",
    inStock: 4,
    fastDelivery: false,
    rating: 4,
    desc: "The Heart is an emblem of love, sorrow, joy, affection and compassion. It’s symbolic of eternal bonds, desire, and spiritual aspirations",
  },
  {
    id: 9,
    name: "kelistom Handmade Buddhist String Bracelets for Women Men Boys Girls, Tibetan Adjustable Woven Rope Bracelet",
    price: 6,
    img: "https://m.media-amazon.com/images/I/51jtDjtrkXL._AC_UL320_.jpg",
    inStock: 4,
    fastDelivery: true,
    rating: 4,
    desc: "6” to up to 10.2”, adjustable",
  },
  {
    id: 10,
    name: "Amazon Essentials Men's Easy to Read Strap Watch",
    price: 17,
    img: "https://m.media-amazon.com/images/I/81SkKZjDDyL._AC_UL320_.jpg",
    inStock: 4,
    fastDelivery: false,
    rating: 4,
    desc: "Matte black dial with silver-tone luminous hands and easy to read white Arabic numerals; printed outer minute track",
  },
  {
    id: 11,
    name: "Timex Easy Reader 38mm Leather Strap Watch",
    price: 39,
    img: "https://m.media-amazon.com/images/I/71UaIg8z3jL._AC_UL320_.jpg",
    inStock: 4,
    fastDelivery: true,
    rating: 5,
    desc: "Adjustable brown 20 millimeter genuine leather strap fits up to 8-inch wrist circumference",
  },
  {
    id: 12,
    name: "SAMSUNG Galaxy S21 FE 5G Cell Phone, Factory Unlocked Android Smartphone, 128GB, 120Hz Display Screen, Pro Grade Camera, All Day Intelligent Battery, US Version, Olive",
    price: 594,
    img: "https://m.media-amazon.com/images/I/61pP6pemX3L._AC_UY218_.jpg",
    inStock: 2,
    fastDelivery: false,
    rating: 4,
    desc: "SMOOTH SCROLLING: The 120Hz display delivers a super smooth scroll, with optimized refresh rate, and a fast touch response gives seamless visuals in both work and play.Form_factor : Smartphone",
  },
  {
    id: 13,
    name: "Apple iPhone XR, 64GB, Black - Unlocked (Renewed)",
    price: 220,
    img: "https://m.media-amazon.com/images/I/717KHGCJ6eL._AC_UY218_.jpg",
    inStock: 2,
    fastDelivery: true,
    rating: 4,
    desc: "This phone is unlocked and compatible with any carrier of choice on GSM and CDMA networks",
  },
  {
    id: 14,
    name: "iPhone 13 Pro Max, 256GB, Sierra Blue - Unlocked (Renewed Premium)",
    price: 1101,
    img: "https://m.media-amazon.com/images/I/61i8Vjb17SL._AC_UY218_.jpg",
    inStock: 2,
    fastDelivery: false,
    rating: 4,
    desc: "Tested for battery health and guaranteed to come with a battery that exceeds 90% of original capacity.",
  },
  {
    id: 15,
    name: "Samsung Galaxy S10, 128GB, Prism Blue - Unlocked (Renewed)",
    price: 173,
    img: "https://m.media-amazon.com/images/I/61dldTSpV-L._AC_UY218_.jpg",
    inStock: 2,
    fastDelivery: true,
    rating: 4,
    desc: "This phone is unlocked and compatible with any carrier of choice on GSM and CDMA networks ",
  },
];
